//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.0
//     from Assets/Samples/SimpleDemo/GestureInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GestureInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GestureInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GestureInputAction"",
    ""maps"": [
        {
            ""name"": ""Fire"",
            ""id"": ""936b4ac6-c53e-4138-92a7-1f23cf8bf10a"",
            ""actions"": [
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Value"",
                    ""id"": ""a168c9f9-0845-44f8-b667-05051edf1d7e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""CircleGesture"",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2e7a30ad-dad8-42db-9e7f-13e6c59b4b5e"",
                    ""path"": ""<Pointer>/position"",
                    ""interactions"": ""CircleGesture"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Fire
        m_Fire = asset.FindActionMap("Fire", throwIfNotFound: true);
        m_Fire_Trigger = m_Fire.FindAction("Trigger", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Fire
    private readonly InputActionMap m_Fire;
    private List<IFireActions> m_FireActionsCallbackInterfaces = new List<IFireActions>();
    private readonly InputAction m_Fire_Trigger;
    public struct FireActions
    {
        private @GestureInputAction m_Wrapper;
        public FireActions(@GestureInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Trigger => m_Wrapper.m_Fire_Trigger;
        public InputActionMap Get() { return m_Wrapper.m_Fire; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FireActions set) { return set.Get(); }
        public void AddCallbacks(IFireActions instance)
        {
            if (instance == null || m_Wrapper.m_FireActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FireActionsCallbackInterfaces.Add(instance);
            @Trigger.started += instance.OnTrigger;
            @Trigger.performed += instance.OnTrigger;
            @Trigger.canceled += instance.OnTrigger;
        }

        private void UnregisterCallbacks(IFireActions instance)
        {
            @Trigger.started -= instance.OnTrigger;
            @Trigger.performed -= instance.OnTrigger;
            @Trigger.canceled -= instance.OnTrigger;
        }

        public void RemoveCallbacks(IFireActions instance)
        {
            if (m_Wrapper.m_FireActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFireActions instance)
        {
            foreach (var item in m_Wrapper.m_FireActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FireActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FireActions @Fire => new FireActions(this);
    public interface IFireActions
    {
        void OnTrigger(InputAction.CallbackContext context);
    }
}
